### ISSUE TITLE
Wrong transport name (?) in the generated SDP for INVITE

### ISSUE THREAD

**Issue by leonid-xorcom** [miconda/sipexer#10]
The SDP in the generated INVITE contains transport RTP in the media description line:
<m=audio 32962 RTP 0 8 101>

I think that the transport should be RTP/AVP instead of just RTP.

**Comment by miconda** [comment]
Indeed, thanks for the report! Should be fixed now.

Till a new release is out, if building from sources is not an easy option, one could put the sdp teplante inside a file and pass it via `-template-body-file` param.

Closing this one.
