### ISSUE TITLE
Getting write error

### ISSUE THREAD

**Issue by davidcsi** [miconda/sipexer#13]
Hello, 

I'm getting this intermittently, can't figure out why...
```
[error] [sipexer.go:1389] main.SIPExerSendBytes(): error writing - write udp4 172.26.210.130:50600->172.26.209.100:5060: i/o timeout
```

when call is answered.
This is my command:

```
./sipexer -invite -vl 9 -co -com \
	-fuser '+numberFrom' \
	-tuser numberTo \
	-rn numberTo \
	-cb \
	-sw 1000 -sd -timer-t1 60000 -su \
	udp:172.26.209.100:5060
```

**Comment by miconda** [comment]
The error comes from golang core lib, is the application listening on 172.26.209.100:5060 still running?

There is sort of `connected udp` which leverages `icmp` for detecting when the target is available or not.

**Comment by davidcsi** [comment]
Thanks Daniel, yes it is. It's a kamailio.

**Comment by miconda** [comment]
Try to capture icmp packets with wireshark/tcpdump and see if you notice anything suspect there.

**Comment by miconda** [comment]
You should also watch the sockets with netstat and see if the write queue for 172.26.210.130:50600 is high, write on udp socket can fail if its buffer is full and cannot push more there.

**Comment by miconda** [comment]
I am going to close this one if no further details are posted.
