### ISSUE TITLE
Missing Max-Forwards header

### ISSUE THREAD

**Issue by vasilakisfil** [miconda/sipexer#17]
Seems like the client doesn't add the mandatory (by RFC3261) `Max-Forwards` header.

**Comment by miconda** [comment]
At this moment you can provide own template file for message with `-tf`. Or try to provide it with `-xh`. See the help printed by `-h`.

It the future it can be added in the internal template

**Comment by vasilakisfil** [comment]
yes for now I add it as a custom header using `-xh`.

**Comment by miconda** [comment]
It is now included in the internal template.
