### ISSUE TITLE
sipexer IPv6

### ISSUE THREAD

**Issue by summitrabz** [miconda/sipexer#18]
Hi @miconda 

Thank you for the great tool. I'm starting to like this tool more than sipping.

I'm running into a tiny issue using Sipexer over IPv6 - Below is the error:

` $./sipexer fe80::acdb:69ff:feb5:7eaf

[error] [sipexer.go:726] main.main(): invalid destination address: fe80::acdb:69ff:feb5:7eaf
[root@ opt]# ./sipexer [fe80::acdb:69ff:feb5:7eaf]

panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
github.com/miconda/sipexer/sgsip.SGAddrTypeEx({0x0, 0x0})
        /github/workspace/sgsip/sgsip.go:239 +0xb7
github.com/miconda/sipexer/sgsip.SGSIPParseSocketAddress({0xfff83881, 0x1b}, 0xa43bd4c)
        /github/workspace/sgsip/sgsip.go:356 +0x56
main.main()
        /github/workspace/sipexer.go:724 +0xeb4
[root@opt]# ./sipexer [::1]

panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
github.com/miconda/sipexer/sgsip.SGAddrTypeEx({0x0, 0x0})
        /github/workspace/sgsip/sgsip.go:239 +0xb7
github.com/miconda/sipexer/sgsip.SGSIPParseSocketAddress({0xffd2c897, 0x5}, 0x9c3bd4c)
        /github/workspace/sgsip/sgsip.go:356 +0x56
main.main()
        /github/workspace/sipexer.go:724 +0xeb4

[root@t]# ./sipexer sip:[fe80::acdb:69ff:feb5:7eaf]:5060

[error] [sipexer.go:1814] main.SIPExerSendUDP(): error: dial udp6 [fe80::acdb:69ff:feb5:7eaf]:5060: connect: invalid argument
[root@ opt]# ./sipexer udp:[fe80::acdb:69ff:feb5:7eaf]:5060

[error] [sipexer.go:1814] main.SIPExerSendUDP(): error: dial udp6 [fe80::acdb:69ff:feb5:7eaf]:5060: connect: invalid argument
`

Any help would be appreciated! :)

It seems to support TLS, would love test TLS using SIPEXER

**Comment by miconda** [comment]
I pushed a commit for it, referenced above. To test, you have to build sipexer using the latest git main branch. You can try variants using IPv6 and report if there are still issues. When only IPv6 is provided, it still has to be given in between [ ].

**Comment by summitrabz** [comment]
@miconda  Thank you so much for your prompt response and action. Much appreciated.

My scenario is to test IPv6 using SIPexer and Kamailio on the same box. So, I have a Kamailio, listening on:
             udp: fe80::7cc0:4fff:fe15:4ceb:5060
             udp: ::1:5060
             tcp: fe80::7cc0:4fff:fe15:4ceb:5060
             tcp: ::1:5060

I can send OPTIONS to [::1] and receive 200OK. But when I try to send it [fe80::7cc0:4fff:fe15:4ceb] I get `connect: invalid argument`. 

# ./sipexer [fe80::7cc0:4fff:fe15:4ceb]

[error] [sipexer.go:1814] main.SIPExerSendUDP(): error: dial udp6 [fe80::7cc0:4fff:fe15:4ceb]:5060: connect: invalid argument
`

I could successfully ping IPv6
ping fe80::7cc0:4fff:fe15:4ceb
```
PING fe80::7cc0:4fff:fe15:4ceb(fe80::7cc0:4fff:fe15:4ceb) 56 data bytes
64 bytes from fe80::7cc0:4fff:fe15:4ceb%eth1: icmp_seq=1 ttl=64 time=0.359 ms
64 bytes from fe80::7cc0:4fff:fe15:4ceb%eth1: icmp_seq=2 ttl=64 time=0.331 ms
64 bytes from fe80::7cc0:4fff:fe15:4ceb%eth1: icmp_seq=3 ttl=64 time=0.330 ms
```

I'm still figuring out the root cause of issue.

**Comment by miconda** [comment]
Pushed a commit to print the parameters of the function that fails, because it is at an intermediary step where it tries to figure out what local ip is going to be used for communication. Maybe you can run with latest git version and see what is printed, maybe it helps with troubleshooting.

**Comment by miconda** [comment]
Closing, `./sipexer [IPv6]` works fine for me. Open a new issues if the latest git version still gives errors for you, providing the logs.
