### ISSUE TITLE
Unknown CA

### ISSUE THREAD

**Issue by ghenry** [miconda/sipexer#29]
Hi,

Are there any options to ignore this?

```
$ ./sipexer tls:127.0.0.1:8088
[error] [sipexer.go:1939] main.SIPExerSendTLS(): error: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Thanks.

**Comment by ghenry** [comment]
Nevermind:

`./sipexer -tls-insecure tls:127.0.0.1:8088`

Just adding TLS to https://github.com/SentryPeer

All good! Love this tool!

**Comment by duraki** [comment]
Sorry for paging post-closed issue,  but this should deffo sit in the repository's `README.md` as visiting the closed Issue tab is just lazy. Thanks for working on it
